# Generated by Django 4.1.1 on 2022-09-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarefas',
            new_name='Tasks',
        ),
    ]
